language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmagic-dev

install:
  - python setup.py build --enable-magic --enable-dotnet
  - python setup.py install

script:
  - python tests.py
